# Generated by Django 3.2.4 on 2021-06-03 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=500)),
                ('op_a', models.CharField(max_length=300)),
                ('op_b', models.CharField(max_length=300)),
                ('op_c', models.CharField(max_length=300)),
                ('op_d', models.CharField(max_length=300)),
                ('marks_assigned', models.DecimalField(decimal_places=2, max_digits=4)),
                ('correct_choice', models.CharField(choices=[('a', 'option a'), ('b', 'option b'), ('c', 'option c'), ('d', 'option d')], default='a', max_length=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.BooleanField(default=False)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
