# Generated by Django 3.2.4 on 2021-06-04 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentScores',
            new_name='AssessmentScore',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='op_a',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='op_b',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='op_c',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='op_d',
            new_name='option_d',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='que',
            new_name='question',
        ),
    ]
