# Generated by Django 3.2.4 on 2021-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20210604_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentscore',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
